#!/bin/bash
filename=./sounds/doremi.wav
out_filename_raw=./output/doremi_PSD.raw
out_filename_dat=./output/doremi_PSD.dat
sox $filename -t raw -c 1 - | ./bin/identify_f0 8192  
#> $out_filename_raw
#./bin/read_data2  $out_filename_raw > $out_filename_dat